# render.yaml - Render.com configuration
services:
  - type: web
    name: hanamal24-events
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: AIRTABLE_TOKEN
        value: patfEh10eMje6sACP.b76a7392aee5a154df6fa1910991097e2eeb0f61984daff39ac15d4f0d4a1ec6
      - key: AIRTABLE_BASE
        value: appeW41fJAbVdeWoU
      - key: BASE_URL
        value: https://hanamal24-events.onrender.com
      - key: SITE_NAME
        value: Hanamal 24
      - key: SITE_CITY
        value: Haifa
      - key: SITE_COUNTRY
        value: IL
      - key: CUISINE
        value: French
