name: Test Build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Test build without Airtable
        run: |
          echo "Testing build without Airtable data..."
          AIRTABLE_TOKEN=test AIRTABLE_BASE=test npm run build
          
      - name: List dist contents
        run: |
          echo "Dist folder contents:"
          ls -la dist/
          echo "Files in dist:"
          find dist/ -type f
